package automod_legacy

// This list is in alphabethical order
// Open a pr or bug me on discord if you want a word added
var BuiltinSwearWords = map[string]bool{
	"anal":        true,
	"anus":        true,
	"arse":        true,
	"ballsack":    true,
	"biatch":      true,
	"blowjob":     true,
	"bollock":     true,
	"boob":        true,
	"boobs":       true,
	"buttplug":    true,
	"clitoris":    true,
	"cock":        true,
	"cum":         true,
	"cunt":        true,
	"dildo":       true,
	"dyke":        true,
	"erection":    true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"fellate":     true,
	"fellatio":    true,
	"fudgepacker": true,
	"genitals":    true,
	"jizz":        true,
	"knobend":     true,
	"labia":       true,
	"masturbate":  true,
	"muff":        true,
	"Nigger":      true,
	"pube":        true,
	"queer":       true,
	"scrotum":     true,
	"sex":         true,
	"slut":        true,
	"smegma":      true,
	"spunk":       true,
	"tit":         true,
	"tranny":       true,
	"trannies":     true,
	"tosser":      true,
	"turd":        true,
	"twat":        true,
	"vagina":      true,
	"wank":        true,
	"whore":       true,
	"tits":        true,

}
